### ISSUE TITLE
Be able to run a second container/instance in Docker for Windows

### ISSUE THREAD

**Issue by cahiatt** [wouterdebie/locast2tuner#89]
Maybe this feature is arleady there and is just a defeciency in my Docker skills. I'd like to be able to run a second instance for additional tuners. I have TWO paid Locast accounts and would like to run one container for account 1 and the second for account 2. 

I've tried changing the container name and ports for the second instance but they will not run together. Starting one just kills the other. Has anyone gotten two instances to run simultaneously in Docker?

**Comment by eiddor** [comment]
You should be able to do this without a problem as long as you keep things separated.

Here's what the `docker-compose.yaml` file would look like:

```
version: '3'
services:
  locast2tuner1:
    image: ghcr.io/wouterdebie/locast2tuner
    container_name: locast2tuner1
    environment:
      - l2t_username=account1_email
      - l2t_password=account1_password
    ports:
      - 6077:6077
    restart: unless-stopped

  locast2tuner2:
    image: ghcr.io/wouterdebie/locast2tuner
    container_name: locast2tuner2
    environment:
      - l2t_username=account2_email
      - l2t_password=account2_password
    ports:
      - 6078:6077
    restart: unless-stopped
```
